### ISSUE TITLE
Question: Using cog URIs that require authentication?

### ISSUE THREAD

**Issue by mdillon-airbus** [developmentseed/cogeo-mosaic#188]
The titiler code works with secured Azure assets if I specify a valid AZURE_STORAGE_CONNECTION_STRING.

My cog uris then have the form:

/vsiaz/sample1/cog1.tif
/vsiaz/sample1/cog2.tif

etc

And I can call titiler like this:

https://mytitilersite.example.net/cog/info?url=%2Fvsiaz%2Fsample1%2Fcog1.tif

How can I use cogeo-mosaic without pulling the cog files down locally?

To clarify what hasn't worked - neither the outputs of the /cog/info or cog/info.geojson seem to be supported when using the "create-from-features" option.  An error is emitted:

`Traceback (most recent call last):
  File "/mycode/venv/bin/cogeo-mosaic", line 8, in <module>
    sys.exit(cogeo_cli())
  File "/mycode/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mycode/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mycode/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mycode/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mycode/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mycode/venv/lib/python3.8/site-packages/cogeo_mosaic/scripts/cli.py", line 164, in create_from_features
    list(features),
  File "/mycode/venv/lib/python3.8/site-packages/cligj/features.py", line 38, in normalize_feature_inputs
    for feature in iter_features(iter(src)):
  File "/mycode/venv/lib/python3.8/site-packages/cligj/features.py", line 136, in iter_features
    obj = json.loads(text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by vincentsarago** [comment]
@mdillon-airbus sorry for missing this.

It seems there is an issue with the JSON (features). would you be able to share it?

**Comment by mdillon-airbus** [comment]
@vincentsarago 

> It seems there is an issue with the JSON (features). would you be able to share it?

Is there a debug flag to examine the intermediate json when calling "cogeo-mosaic create-from-features"?

**Comment by vincentsarago** [comment]
wait I miss understood the issue?

> To clarify what hasn't worked - neither the outputs of the /cog/info or cog/info.geojson seem to be supported when using the "create-from-features" option. An error is emitted:

yeah it might not work because you need to pass a feature collection or a list of features to `cogeo-mosaic create-from-features` while ` /cog/info or cog/info.geojson` return feature.

I'm still not 💯 sure what you are trying to do. Can you share all the steps that you are doing?

**Comment by mdillon-airbus** [comment]
I may understand what happened - a simple 'create' is all that was needed with a list of the cogs as the input file (although I could have sworn I tried that).

Here is what's working for me:

```
export AZURE_STORAGE_CONNECTION_STRING="this is secret"

cogeo-mosaic create \
remote_cog_list.txt \
--minzoom 9 \
--maxzoom 19 \
--name "mosaic-sample" \
--description "Sample" \
-o "mosaic_example.json"
```

where 'remote_cog_list.txt' simply has:

```
/vsiaz/sample1/cog1.tif
/vsiaz/sample1/cog2.tif
/vsiaz/sample1/cog3.tif
/vsiaz/sample1/cog4.tif
```
