### ISSUE TITLE
improve error if file in list is not accessible

### ISSUE THREAD

**Issue by andrewharvey** [developmentseed/cogeo-mosaic#39]
When running `cogeo-mosaic create` I encountered the following error:

```
Get files footprint
  [####################################]  100%          
Traceback (most recent call last):
  File ".local/bin/cogeo-mosaic", line 8, in <module>
    sys.exit(cogeo_cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File ".local/lib/python3.8/site-packages/cogeo_mosaic/scripts/cli.py", line 74, in create
    mosaic_spec = create_mosaic(
  File ".local/lib/python3.8/site-packages/cogeo_mosaic/utils.py", line 248, in create_mosaic
    minzoom = max(minzoom)
ValueError: max() arg is an empty sequence
```

After some debugging it was because I hadn't set the right AWS env variables so my files in my list were not accessible, after setting the AWS variables it worked.

There should probably be a check somewhere and logging if a file in the list wasn't accessible.

**Comment by andrewharvey** [comment]
The https://github.com/developmentseed/cogeo-mosaic/issues/35#issuecomment-593630485 suggestion at helps reveal the error.

I think my issue now is something doesn't like AWS_S3_ENDPOINT which I'm using to use with Digital Ocean Spaces, so certainly more error logging has helped debug this.
