### ISSUE TITLE
Wrong DynamoDB exception handling

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#75]
In my own [older DynamoDB upload script](https://github.com/kylebarron/naip-lambda/blob/9629c543e41b3bb095258e8315e3b2ba9dc17aea/code/dynamodb_upload.py#L58-L71), I have
```py
    # Note: errors if table already exists
    try:
        response = client.create_table(
            AttributeDefinitions=attr_defs,
            TableName=mosaicid,
            KeySchema=key_schema,
            BillingMode=billing_mode)
        print('creating table')

        # If I put this outside the try/except block, could wait forever if
        # unable to create table
        client.Table(mosaicid).wait_until_exists()
    except boto3.client('dynamodb').exceptions.ResourceInUseException:
        print('unable to create table, may already exist')
```

In `cogeo-mosaic` that got changed to:
https://github.com/developmentseed/cogeo-mosaic/blob/68958a3dae5c26fdfc30b2f635c19201b88fcb30/cogeo_mosaic/backends/dynamodb.py#L126-L139

This doesn't work anymore because `self.client` is an instance of `boto3.resource("dynamodb")` not `boto3.client`.

So you get an exception while trying to handle the exception:
```
Traceback (most recent call last):
  File "/Users/kyle/github/mapping/cogeo-tiling/cogeo-mosaic/cogeo_mosaic/backends/dynamodb.py", line 131, in _create_table
    BillingMode=billing_mode,
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the CreateTable operation: Table already exists: usgs-topo-latest.v1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/local/anaconda3/bin/cogeo-mosaic", line 11, in <module>
    load_entry_point('cogeo-mosaic', 'console_scripts', 'cogeo-mosaic')()
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kyle/github/mapping/cogeo-tiling/cogeo-mosaic/cogeo_mosaic/scripts/cli.py", line 105, in upload
    mosaic.write()
  File "/Users/kyle/github/mapping/cogeo-tiling/cogeo-mosaic/cogeo_mosaic/backends/dynamodb.py", line 62, in write
    self._create_table()
  File "/Users/kyle/github/mapping/cogeo-tiling/cogeo-mosaic/cogeo_mosaic/backends/dynamodb.py", line 137, in _create_table
    except self.client.exceptions.ResourceInUseException:
AttributeError: 'dynamodb.ServiceResource' object has no attribute 'exceptions'
```

**Comment by vincentsarago** [comment]
@kylebarron so we should use `boto3.client('dynamodb').exceptions.ResourceInUseException:` ?

**Comment by kylebarron** [comment]
Yes, 
```
except boto3.client('dynamodb').exceptions.ResourceInUseException:
````
works just fine
